title: Contenu du site

options:
  changeTitle: false

columns:
  left:
    width: 1/4
    fields:
      files:
        label: Fichiers PDF
        type: files
        layout: small
        uploads:
          template: pdf

  center:
    width: 2/4
    sections:
      pages_infos:
        label: Pages principales
        status: listed
        type: pages
        layout: cards
        image:
          query: false
          ratio: 3/1
          back: "rgb(196 226 254)"
        text: "{{ page.intendedTemplate }}"
        templates:
          - home
          - equipe
          - contact
          - geneve-aeroport

      pages_system:
        label: Paramètres système
        type: pages
        layout: cards
        parent: site
        image:
          query: false
          ratio: 3/1
          back: "rgb(254 226 196)"
        text: "{{ page.title }}"
        status: listed
        templates:
          - footer

  right:
    width: 1/4
    sections:
      pages_actualitees :
        label: Actualités
        type: pages
        layout: cards
        create: false
        image:
          query: false
          ratio: 3/1
          back: "rgb(254 196 226)"
        text: "{{ page.children.count }} articles"
        templates:
          - actualities



