title: Contenu du site

columns:
  left:
    width: 2/3
    sections:
      pages_infos:
        label: Pages
        type: pages
        layout: cards
        image:
          query: false
          ratio: 3/1
          back: "rgb(196 226 254)"
        templates:
          - home
          - contact

  right:
    width: 1/3
    sections:
      pages_actualities:
        label: Pages
        type: pages
        layout: cards
        image:
          query: false
          ratio: 3/1
          back: "rgb(196 226 254)"
        templates:
          - actualities



